### ISSUE TITLE
Crashes when invoked on calibre

### ISSUE THREAD

**Issue by stuartlangridge** [ubuntu-mate/mate-hud#27]
When attempting to summon the HUD in a Calibre window (either the main book list or the book editor), the following traceback is generated from an error. Later, apport pops up with its complaint. (And the HUD doesn't work in Calibre, of course, given the error.)

```
Traceback (most recent call last):
  File "/usr/lib/mate-hud/mate-hud", line 464, in hud
    appmenu_success = try_appmenu_interface(int(window_id, 16))
  File "/usr/lib/mate-hud/mate-hud", line 299, in try_appmenu_interface
    expanse_all_menu_with_dbus(dbusmenu_root_item[1], True, "")
  File "/usr/lib/mate-hud/mate-hud", line 277, in expanse_all_menu_with_dbus
    dbusmenu_object_iface.AboutToShow(item_id)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/utils/dbus_service.py", line 924, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/calibre/calibre/gui2/dbus_export/menu.py", line 349, in AboutToShow
    return self.menu.handle_about_to_show(ac)
  File "/usr/lib/calibre/calibre/gui2/dbus_export/menu.py", line 268, in handle_about_to_show
    ac.menu().aboutToShow.emit()
AttributeError: 'ExportedMenuBar' object has no attribute 'aboutToShow'

```

**Comment by vkareh** [comment]
I can't get this error to come up, but I do get the following message:
```
INFO:root:Unable to access dbusmenu items.
```
This also happens with VLC
