### ISSUE TITLE
mate-hud in plasma

### ISSUE THREAD

**Issue by RaitaroH** [ubuntu-mate/mate-hud#37]
```
$ python3 /usr/lib/mate-hud/mate-hud 2>&1 | tee -a ~/Desktop/mate-hud.log

Gtk-Message: 20:53:18.893: Failed to load module "/home/raitaro/appmenu-gtk-module"
(mate-hud:7244): Gtk-WARNING **: 20:53:18.897: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
(mate-hud:7244): Gtk-WARNING **: 20:53:18.897: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
(mate-hud:7244): Gtk-WARNING **: 20:53:18.898: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Gtk-Message: 20:53:18.918: Failed to load module "appmenu-gtk-moduleppmenu-gtk-module"
INFO:root:Press <Alt>space to handle keybinding
[1]    7244 terminated  python3 /usr/lib/mate-hud/mate-hud 2>&1 |
7245 done        tee -a ~/Desktop/mate-hud.log
```
Right there mate-hud crashed... that is the menu was not displayed, and the `Alt` key kept being active thus making any keyboard input... kinda impossible (tty works though). And in my case `Alt` plus mouse means move or resize or transparency (wheel) so... yeah, tty + htop kill is the only way to get this to behave.

**Comment by RaitaroH** [comment]
Sorry... I don't have any useful output.

**Comment by RaitaroH** [comment]
Some other stuff appeared:

```
INFO:root:Press <Alt>space to handle keybinding
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/Xlib/protocol/rq.py", line 1294, in __getattr__
return self._data[attr]
KeyError: 'state'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib/mate-hud/mate-hud", line 603, in run
modifiers = event.state & self.known_modifiers_mask
File "/usr/lib/python3/dist-packages/Xlib/protocol/rq.py", line 1298, in __getattr__
raise AttributeError(attr)
AttributeError: state
```

**Comment by RaitaroH** [comment]
`Gtk-Message: 23:11:19.695: Failed to load module "/home/raitaro/appmenu-gtk-module"`

:thinking: 
```
$ apt search appmenu-gtk-module
Sorting... Done
Full Text Search... Done
appmenu-gtk-module-common/now 0.7.1-1 all [installed,local]
Common files for GtkMenuShell D-Bus exporter
```

**Comment by RaitaroH** [comment]
```
▶ python3 /usr/lib/mate-hud/mate-hud
Gtk-Message: 18:06:34.087: Failed to load module "/home/raitaro/appmenu-gtk-module"
(mate-hud:14336): Gtk-WARNING **: 18:06:34.092: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
(mate-hud:14336): Gtk-WARNING **: 18:06:34.092: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
(mate-hud:14336): Gtk-WARNING **: 18:06:34.092: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn'tbe used anymore. It will be removed in a future version
Gtk-Message: 18:06:34.113: Failed to load module "appmenu-gtk-moduleppmenu-gtk-module"
INFO:root:Press Alt_L to handle keybinding
ERROR:dbus.proxies:Introspect error on :1.758:/MenuBar/1: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.758 was not provided by any .service files
Traceback (most recent call last):
File "/usr/lib/mate-hud/mate-hud", line 464, in hud
appmenu_success = try_appmenu_interface(int(window_id, 16))
File "/usr/lib/mate-hud/mate-hud", line 264, in try_appmenu_interface
dbusmenu_root_item = dbusmenu_object_iface.GetLayout(0, 0, ["label", "children-display"])
File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
return self._proxy_method(*args, **keywords)
File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
**keywords)
File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.758 was not provided by any .service files
Error in sys.excepthook:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_mate-hud_mate-hud.1000.crash'
Original exception was:
Traceback (most recent call last):
File "/usr/lib/mate-hud/mate-hud", line 464, in hud
appmenu_success = try_appmenu_interface(int(window_id, 16))
File "/usr/lib/mate-hud/mate-hud", line 264, in try_appmenu_interface
dbusmenu_root_item = dbusmenu_object_iface.GetLayout(0, 0, ["label", "children-display"])
File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
return self._proxy_method(*args, **keywords)
File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
**keywords)
File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.758 was not provided by any .service files
ERROR:root:Error processing keybinding: time
ERROR:root:Error processing keybinding: time
ERROR:root:Error processing keybinding: time
ERROR:root:Error processing keybinding: time
```

**Comment by RaitaroH** [comment]
hmm. I switched from Alt_L to Alt_R and it works much better. Adding some extra things to exceptions didn't quite work for me (at all) but with Alt_R there are no more conflicts. Can't say about crashing yet,

**Comment by kupiqu** [comment]
- Alt_R triggers an error in my system:

```
Traceback (most recent call last):
  File "/usr/lib/mate-hud/mate-hud", line 712, in <module>
    keybinder.grab(shortcut)
  File "/usr/lib/mate-hud/mate-hud", line 551, in grab
    self.keycode = self.keymap.get_entries_for_keyval(keyval).keys[0].keycode
IndexError: list index out of range
```

- Alt_Gr does not trigger an error but doesn't work.

- Alt_L interferes too much with my system.

- Alternatives such as shortcut combinations like '<Alt>h' work at first but then hang the keyboard input (which I could fix by killing mate-hud via ssh from the phone).

I'll try again if https://github.com/ubuntu-mate/mate-hud/issues/30 is fixed

**Comment by kupiqu** [comment]
I started using @Zren fork in plasma. Unfortunately, issue #30 is still present so I had to default to Alt_L, which is a shortcut I use in latte-dock for triggering the application launcher.

For the case it is useful, I could identify the following issues:

- Pressing Alt_L first triggers the application launcher in latte. Most of the times (but not always) the application launcher disappears and the HUD menu is triggered. However, the HUD menu frequently appears at top left location of the screen instead of at the window location.
 
- In order to only trigger the application launcher, one needs to hold Alt_L for a while and then release.

**Comment by kupiqu** [comment]
I redirected the application launcher to Ctrl in kwinrc and it seems to be working better now...

**Comment by RaitaroH** [comment]
@kupiqu @Zren I was wondering if `Meta` to trigger the menu, in my case krunner works for you? For me is not and I am not sure if mate-hud this is the reason.

**Comment by kupiqu** [comment]
It works fine for me.

**Comment by kupiqu** [comment]
> As in, using Meta to trigger the HUD? We need to unbind the Meta key from KWin/KRunner then.

Oh I see, I misunderstood it was about using Meta for the HUD. Didn't try that, sorry for the confusion.

**Comment by RaitaroH** [comment]
I see. Thank you.

**Comment by RaitaroH** [comment]
@Zren your version of the code breaks mate-hud for Waterfox-kde 56.2.4.

**Comment by kupiqu** [comment]
> I recently installed Manjaro, so I'm not certain why firefox doesn't work for me atm.

Firefox works for me just fine in KDE neon 18.04

**Comment by flexiondotorg** [comment]
I don't use KDE so can't support it. Glad to see @Zren has created a fork for Plasma use. I recommend KDE user head there :+1:

**Comment by flexiondotorg** [comment]
https://github.com/Zren/plasma-hud
