### ISSUE TITLE
HUD not working in Google Chrome

### ISSUE THREAD

**Issue by huyhoang8398** [ubuntu-mate/mate-hud#54]
Pressing Alt not showing HUD
The global menu works fine
- OS: Ubuntu 20.04.4

**Comment by huyhoang8398** [comment]
CapAmb:	0000000000000000
 NoNewPrivs:	0
 Seccomp:	0
 Seccomp_filters:	0
 Speculation_Store_Bypass:	thread vulnerable
 SpeculationIndirectBranch:	conditional enabled
 Cpus_allowed:	ff
 Cpus_allowed_list:	0-7
 Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
 Mems_allowed_list:	0
 voluntary_ctxt_switches:	264
 nonvoluntary_ctxt_switches:	13
PythonArgs: ['/usr/lib/mate-hud/mate-hud']
Traceback:
 Traceback (most recent call last):
   File "/usr/lib/mate-hud/mate-hud", line 472, in hud
     appmenu_success = try_appmenu_interface(int(window_id, 16))
   File "/usr/lib/mate-hud/mate-hud", line 301, in try_appmenu_interface
     expanse_all_menu_with_dbus(dbusmenu_root_item[1], True, "")
   File "/usr/lib/mate-hud/mate-hud", line 279, in expanse_all_menu_with_dbus
     dbusmenu_object_iface.AboutToShow(item_id)
   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
     return self._connection.call_blocking(self._named_service,
   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
     reply_message = self.send_message_with_reply_and_block(
 dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Failed: error occurred in AboutToShow
UserGroups: adm cdrom dip lpadmin lxd plugdev sambashare sudo
_LogindSession: c2
_PythonExceptionQualifier: org.freedesktop.DBus.Error.Failed
